appName: "Scale down config"
assumedRoleArn: "arn:aws:iam::123456789:role/admin-role"
scalingRegions:
  - region: "us-east-1"
    serviceScaleConfigs:
      - service: "kinesis"
        streamArn: "arn:aws:kinesis:us-east-1:123456789012:stream/ScaleUpStream"
        desiredShardCount: 1
      - service: "dynamodb"
        tableName: "ScaleUpTable"
        isIndex: false
        rcu:
          minProvisionedCapacity: 1
          maxProvisionedCapacity: 1000
        wcu:
          minProvisionedCapacity: 1
          maxProvisionedCapacity: 1000
      - service: "ec2"
        asgName: "ScaleUpASG"
        minCount: 1
        maxCount: 10
        desiredCount: 1
      - service: "elasticache"
        clusterId: "ScaleUpCluster"
        engine: "redis"
        nodeCount: 2
        nodesToDelete: [ ]


  - region: "us-west-2"
    serviceScaleConfigs:
      - service: "kinesis"
        streamArn: "arn:aws:kinesis:us-west-2:123456789012:stream/ScaleUpStream"
        desiredShardCount: 1
      - service: "dynamodb"
        tableName: "ScaleUpTable"
        isIndex: false
        rcu:
          minProvisionedCapacity: 1
          maxProvisionedCapacity: 1000
        wcu:
          minProvisionedCapacity: 1
          maxProvisionedCapacity: 1000
      - service: "elasticache"
        clusterId: "ScaleUpCluster"
        engine: "redis"
        nodeCount: 2
        nodesToDelete:
          - "0001"
          - "0002"