/**
 * pr-tool.ts — PR creation tool (OpenCode 1.4.x plugin)
 */
import { tool } from '@opencode-ai/plugin';
import { execSync } from 'child_process';
const GITHUB_USER_TOKEN = process.env.GITHUB_USER_TOKEN ?? '';
const CODEPILOT_REPO_URL = process.env.CODEPILOT_REPO_URL ?? '';
const CODEPILOT_SESSION_ID = process.env.CODEPILOT_SESSION_ID ?? '';
const WORKSPACE = process.env.CODEPILOT_WORKSPACE ?? '/workspace';
async function createGithubPR(owner, repo, payload) {
    const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
        method: 'POST',
        headers: {
            Authorization: `Bearer ${GITHUB_USER_TOKEN}`,
            'Content-Type': 'application/json',
            'User-Agent': 'CodePilot',
            Accept: 'application/vnd.github.v3+json',
        },
        body: JSON.stringify(payload),
    });
    if (!res.ok)
        throw new Error(`GitHub API error ${res.status}: ${await res.text()}`);
    return res.json();
}
function git(args) {
    return execSync(`git ${args}`, { cwd: WORKSPACE, encoding: 'utf8' }).trim();
}
function getCurrentBranch() {
    return git('rev-parse --abbrev-ref HEAD');
}
function getDefaultBranch() {
    try {
        return git('symbolic-ref refs/remotes/origin/HEAD --short').replace('origin/', '');
    }
    catch {
        return 'main';
    }
}
function getDiffStat() {
    try {
        return git('diff --stat HEAD~1 HEAD');
    }
    catch {
        return '';
    }
}
const PrToolPlugin = async () => {
    return {
        tool: {
            create_pull_request: tool({
                description: 'Create a GitHub PR with the current changes',
                args: {
                    title: tool.schema.string().describe('PR title (also used as the commit message)'),
                    body: tool.schema.string().describe('PR description summarising what was changed and why'),
                },
                async execute(args) {
                    const { title, body } = args;
                    const match = CODEPILOT_REPO_URL.match(/github\.com[:/]([^/]+)\/([^/.]+)(?:\.git)?$/);
                    if (!match)
                        throw new Error(`Cannot parse GitHub owner/repo from: ${CODEPILOT_REPO_URL}`);
                    const [, owner, repo] = match;
                    git('add -A');
                    try {
                        git(`commit -m ${JSON.stringify(title)}`);
                    }
                    catch {
                        // nothing to commit — fall through and push the existing branch
                    }
                    const branch = getCurrentBranch();
                    git('push -u origin HEAD');
                    const diffStat = getDiffStat();
                    const workerUrl = process.env.CODEPILOT_WORKER_URL ?? '';
                    const sessionLink = workerUrl
                        ? `[View session](${workerUrl}/sessions/${CODEPILOT_SESSION_ID})`
                        : '';
                    const fullBody = [
                        body,
                        '',
                        diffStat ? `## Files changed\n\`\`\`\n${diffStat}\n\`\`\`` : '',
                        sessionLink ? `## Session\n${sessionLink}` : '',
                        '',
                        '---',
                        '_Generated by [CodePilot](https://github.com/Cool-fire/code-agent)_',
                    ]
                        .filter(Boolean)
                        .join('\n');
                    const pr = await createGithubPR(owner, repo, {
                        title,
                        body: fullBody,
                        head: branch,
                        base: getDefaultBranch(),
                    });
                    return `Pull request created: ${pr.html_url}`;
                },
            }),
        },
    };
};
export default { id: 'codepilot.pr-tool', server: PrToolPlugin };
//# sourceMappingURL=pr-tool.js.map